/* tslint:disable */
/* eslint-disable */
/**
 * upload-api
 * Upload API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: hello@upload.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// @ts-ignore
import * as runtime from "../runtime";
import type {
  // @ts-ignore
  AsyncResponse,
  // @ts-ignore
  DeleteFolderBatchRequest,
  // @ts-ignore
  DeleteFolderRequest,
  // @ts-ignore
  ErrorResponse,
  // @ts-ignore
  FolderDetails,
  // @ts-ignore
  ListFolderChildrenResponse,
  // @ts-ignore
  PutFolderRequest
} from "../models";
import {
  // @ts-ignore
  AsyncResponseFromJSON,
  // @ts-ignore
  AsyncResponseToJSON,
  // @ts-ignore
  DeleteFolderBatchRequestFromJSON,
  // @ts-ignore
  DeleteFolderBatchRequestToJSON,
  // @ts-ignore
  DeleteFolderRequestFromJSON,
  // @ts-ignore
  DeleteFolderRequestToJSON,
  // @ts-ignore
  ErrorResponseFromJSON,
  // @ts-ignore
  ErrorResponseToJSON,
  // @ts-ignore
  FolderDetailsFromJSON,
  // @ts-ignore
  FolderDetailsToJSON,
  // @ts-ignore
  ListFolderChildrenResponseFromJSON,
  // @ts-ignore
  ListFolderChildrenResponseToJSON,
  // @ts-ignore
  PutFolderRequestFromJSON,
  // @ts-ignore
  PutFolderRequestToJSON
} from "../models";

export interface DeleteFolderOperationRequest {
  accountId: string;
  deleteFolderRequest: DeleteFolderRequest;
}

export interface DeleteFolderBatchOperationRequest {
  accountId: string;
  deleteFolderBatchRequest: DeleteFolderBatchRequest;
}

export interface GetFolderDetailsRequest {
  accountId: string;
  folderPath: string;
}

export interface ListFolderChildrenRequest {
  accountId: string;
  folderPath: string;
  includeFolders?: boolean;
  includeFiles?: boolean;
  traverseVirtualFolders?: boolean;
  limit?: number;
  cursor?: string;
}

export interface PutFolderOperationRequest {
  accountId: string;
  putFolderRequest: PutFolderRequest;
}

/**
 *
 */
export class FolderApi extends runtime.BaseAPI {
  /**
   * Asynchronously deletes a folder.
   */
  private async deleteFolderRaw(
    requestParameters: DeleteFolderOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<AsyncResponse>> {
    if (requestParameters.accountId === null || requestParameters.accountId === undefined) {
      throw new runtime.RequiredError(
        "accountId",
        "Required parameter requestParameters.accountId was null or undefined when calling deleteFolder."
      );
    }

    if (requestParameters.deleteFolderRequest === null || requestParameters.deleteFolderRequest === undefined) {
      throw new runtime.RequiredError(
        "deleteFolderRequest",
        "Required parameter requestParameters.deleteFolderRequest was null or undefined when calling deleteFolder."
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // authorization-header authentication
    }

    const response = await this.request(
      {
        path: `/v2/accounts/{accountId}/folders`.replace(
          `{${"accountId"}}`,
          encodeURIComponent(String(requestParameters.accountId))
        ),
        method: "DELETE",
        headers: headerParameters,
        query: queryParameters,
        body: DeleteFolderRequestToJSON(requestParameters.deleteFolderRequest)
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, jsonValue => AsyncResponseFromJSON(jsonValue));
  }

  /**
   * Asynchronously deletes a folder.
   */
  async deleteFolder(
    requestParameters: DeleteFolderOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<AsyncResponse> {
    const response = await this.deleteFolderRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Asynchronously deletes multiple folders.
   */
  private async deleteFolderBatchRaw(
    requestParameters: DeleteFolderBatchOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<AsyncResponse>> {
    if (requestParameters.accountId === null || requestParameters.accountId === undefined) {
      throw new runtime.RequiredError(
        "accountId",
        "Required parameter requestParameters.accountId was null or undefined when calling deleteFolderBatch."
      );
    }

    if (
      requestParameters.deleteFolderBatchRequest === null ||
      requestParameters.deleteFolderBatchRequest === undefined
    ) {
      throw new runtime.RequiredError(
        "deleteFolderBatchRequest",
        "Required parameter requestParameters.deleteFolderBatchRequest was null or undefined when calling deleteFolderBatch."
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // authorization-header authentication
    }

    const response = await this.request(
      {
        path: `/v2/accounts/{accountId}/folders/batch`.replace(
          `{${"accountId"}}`,
          encodeURIComponent(String(requestParameters.accountId))
        ),
        method: "DELETE",
        headers: headerParameters,
        query: queryParameters,
        body: DeleteFolderBatchRequestToJSON(requestParameters.deleteFolderBatchRequest)
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, jsonValue => AsyncResponseFromJSON(jsonValue));
  }

  /**
   * Asynchronously deletes multiple folders.
   */
  async deleteFolderBatch(
    requestParameters: DeleteFolderBatchOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<AsyncResponse> {
    const response = await this.deleteFolderBatchRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Gets the settings for this folder.  Returns an empty object if none exist.
   */
  private async getFolderDetailsRaw(
    requestParameters: GetFolderDetailsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<FolderDetails>> {
    if (requestParameters.accountId === null || requestParameters.accountId === undefined) {
      throw new runtime.RequiredError(
        "accountId",
        "Required parameter requestParameters.accountId was null or undefined when calling getFolderDetails."
      );
    }

    if (requestParameters.folderPath === null || requestParameters.folderPath === undefined) {
      throw new runtime.RequiredError(
        "folderPath",
        "Required parameter requestParameters.folderPath was null or undefined when calling getFolderDetails."
      );
    }

    const queryParameters: any = {};

    if (requestParameters.folderPath !== undefined) {
      queryParameters["folderPath"] = requestParameters.folderPath;
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // authorization-header authentication
    }

    const response = await this.request(
      {
        path: `/v2/accounts/{accountId}/folders`.replace(
          `{${"accountId"}}`,
          encodeURIComponent(String(requestParameters.accountId))
        ),
        method: "GET",
        headers: headerParameters,
        query: queryParameters
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, jsonValue => FolderDetailsFromJSON(jsonValue));
  }

  /**
   * Gets the settings for this folder.  Returns an empty object if none exist.
   */
  async getFolderDetails(
    requestParameters: GetFolderDetailsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<FolderDetails> {
    const response = await this.getFolderDetailsRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Lists the children (files and sub-folders) of a folder.
   */
  private async listFolderChildrenRaw(
    requestParameters: ListFolderChildrenRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ListFolderChildrenResponse>> {
    if (requestParameters.accountId === null || requestParameters.accountId === undefined) {
      throw new runtime.RequiredError(
        "accountId",
        "Required parameter requestParameters.accountId was null or undefined when calling listFolderChildren."
      );
    }

    if (requestParameters.folderPath === null || requestParameters.folderPath === undefined) {
      throw new runtime.RequiredError(
        "folderPath",
        "Required parameter requestParameters.folderPath was null or undefined when calling listFolderChildren."
      );
    }

    const queryParameters: any = {};

    if (requestParameters.folderPath !== undefined) {
      queryParameters["folderPath"] = requestParameters.folderPath;
    }

    if (requestParameters.includeFolders !== undefined) {
      queryParameters["includeFolders"] = requestParameters.includeFolders;
    }

    if (requestParameters.includeFiles !== undefined) {
      queryParameters["includeFiles"] = requestParameters.includeFiles;
    }

    if (requestParameters.traverseVirtualFolders !== undefined) {
      queryParameters["traverseVirtualFolders"] = requestParameters.traverseVirtualFolders;
    }

    if (requestParameters.limit !== undefined) {
      queryParameters["limit"] = requestParameters.limit;
    }

    if (requestParameters.cursor !== undefined) {
      queryParameters["cursor"] = requestParameters.cursor;
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // authorization-header authentication
    }

    const response = await this.request(
      {
        path: `/v2/accounts/{accountId}/folders/children`.replace(
          `{${"accountId"}}`,
          encodeURIComponent(String(requestParameters.accountId))
        ),
        method: "GET",
        headers: headerParameters,
        query: queryParameters
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, jsonValue => ListFolderChildrenResponseFromJSON(jsonValue));
  }

  /**
   * Lists the children (files and sub-folders) of a folder.
   */
  async listFolderChildren(
    requestParameters: ListFolderChildrenRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ListFolderChildrenResponse> {
    const response = await this.listFolderChildrenRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates or updates the folder specified by the `folderPath`.  If the folder\'s ancestors do not exist, they will be created automatically (with empty FolderSettings).  *Note:* you don\'t need to create folders before uploading files to them.
   */
  private async putFolderRaw(
    requestParameters: PutFolderOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<FolderDetails>> {
    if (requestParameters.accountId === null || requestParameters.accountId === undefined) {
      throw new runtime.RequiredError(
        "accountId",
        "Required parameter requestParameters.accountId was null or undefined when calling putFolder."
      );
    }

    if (requestParameters.putFolderRequest === null || requestParameters.putFolderRequest === undefined) {
      throw new runtime.RequiredError(
        "putFolderRequest",
        "Required parameter requestParameters.putFolderRequest was null or undefined when calling putFolder."
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // authorization-header authentication
    }

    const response = await this.request(
      {
        path: `/v2/accounts/{accountId}/folders`.replace(
          `{${"accountId"}}`,
          encodeURIComponent(String(requestParameters.accountId))
        ),
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
        body: PutFolderRequestToJSON(requestParameters.putFolderRequest)
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, jsonValue => FolderDetailsFromJSON(jsonValue));
  }

  /**
   * Creates or updates the folder specified by the `folderPath`.  If the folder\'s ancestors do not exist, they will be created automatically (with empty FolderSettings).  *Note:* you don\'t need to create folders before uploading files to them.
   */
  async putFolder(
    requestParameters: PutFolderOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<FolderDetails> {
    const response = await this.putFolderRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
