/* tslint:disable */
/* eslint-disable */
/**
 * upload-api
 * Upload API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: hello@upload.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The type of the job.
 * @export
 */
export const AccountJobType = {
  BatchFolderDeletionJob: "BatchFolderDeletionJob",
  BatchFileDeletionJob: "BatchFileDeletionJob"
} as const;
export type AccountJobType = typeof AccountJobType[keyof typeof AccountJobType];

export function AccountJobTypeFromJSON(json: any): AccountJobType {
  return json as AccountJobType;
}

export function AccountJobTypeToJSON(value?: AccountJobType | null): any {
  return value as any;
}
