/* tslint:disable */
/* eslint-disable */
/**
 * upload-api
 * Upload API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: hello@upload.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const AccountJobStatus = {
  Pending: "Pending",
  Running: "Running",
  Rollback: "Rollback",
  Failed: "Failed",
  Succeeded: "Succeeded",
  Cancelling: "Cancelling",
  Cancelled: "Cancelled"
} as const;
export type AccountJobStatus = typeof AccountJobStatus[keyof typeof AccountJobStatus];

export function AccountJobStatusFromJSON(json: any): AccountJobStatus {
  return json as AccountJobStatus;
}

export function AccountJobStatusToJSON(value?: AccountJobStatus | null): any {
  return value as any;
}
