/* tslint:disable */
/* eslint-disable */
/**
 * upload-api
 * Upload API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: hello@upload.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * AWS Region.
 * @export
 */
export const AwsRegion = {
  UsEast2: "us-east-2",
  UsEast1: "us-east-1",
  UsWest1: "us-west-1",
  UsWest2: "us-west-2",
  AfSouth1: "af-south-1",
  ApEast1: "ap-east-1",
  ApSoutheast3: "ap-southeast-3",
  ApSouth1: "ap-south-1",
  ApNortheast3: "ap-northeast-3",
  ApNortheast2: "ap-northeast-2",
  ApSoutheast1: "ap-southeast-1",
  ApSoutheast2: "ap-southeast-2",
  ApNortheast1: "ap-northeast-1",
  CaCentral1: "ca-central-1",
  EuCentral1: "eu-central-1",
  EuWest1: "eu-west-1",
  EuWest2: "eu-west-2",
  EuSouth1: "eu-south-1",
  EuWest3: "eu-west-3",
  EuNorth1: "eu-north-1",
  MeSouth1: "me-south-1",
  SaEast1: "sa-east-1"
} as const;
export type AwsRegion = typeof AwsRegion[keyof typeof AwsRegion];

export function AwsRegionFromJSON(json: any): AwsRegion {
  return json as AwsRegion;
}

export function AwsRegionToJSON(value?: AwsRegion | null): any {
  return value as any;
}
