/* tslint:disable */
/* eslint-disable */
/**
 * upload-api
 * Upload API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: hello@upload.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// @ts-ignore
import { exists, mapValues } from "../runtime";

// @ts-ignore
import type { UploadPart } from "./UploadPart";
// @ts-ignore
import { UploadPartFromJSON, UploadPartToJSON } from "./UploadPart";

/**
 *
 * @export
 * @interface BeginMultipartUploadResponseUploadParts
 */
export interface BeginMultipartUploadResponseUploadParts {
  /**
   *
   * @type {UploadPart}
   * @memberof BeginMultipartUploadResponseUploadParts
   */
  first: UploadPart;
  /**
   * The number of parts the file will be uploaded with.
   * @type {number}
   * @memberof BeginMultipartUploadResponseUploadParts
   */
  count: number;
}

export function BeginMultipartUploadResponseUploadPartsFromJSON(json: any): BeginMultipartUploadResponseUploadParts {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    first: UploadPartFromJSON(json["first"]),
    count: json["count"]
  };
}

export function BeginMultipartUploadResponseUploadPartsToJSON(
  value?: BeginMultipartUploadResponseUploadParts | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    first: UploadPartToJSON(value.first),
    count: value.count
  };
}
