/* tslint:disable */
/* eslint-disable */
/**
 * upload-api
 * Upload API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: hello@upload.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// @ts-ignore
import { exists, mapValues } from "../runtime";

// @ts-ignore
import type { BeginMultipartUploadResponseUploadParts } from "./BeginMultipartUploadResponseUploadParts";
// @ts-ignore
import {
  BeginMultipartUploadResponseUploadPartsFromJSON,
  BeginMultipartUploadResponseUploadPartsToJSON
} from "./BeginMultipartUploadResponseUploadParts";
// @ts-ignore
import type { FileDetails } from "./FileDetails";
// @ts-ignore
import { FileDetailsFromJSON, FileDetailsToJSON } from "./FileDetails";

/**
 * Response body for BeginMultipartUpload.
 * @export
 * @interface BeginMultipartUploadResponse
 */
export interface BeginMultipartUploadResponse {
  /**
   *
   * @type {FileDetails}
   * @memberof BeginMultipartUploadResponse
   */
  file: FileDetails;
  /**
   * The ID for the multipart file upload.
   * @type {string}
   * @memberof BeginMultipartUploadResponse
   */
  uploadId: string;
  /**
   *
   * @type {BeginMultipartUploadResponseUploadParts}
   * @memberof BeginMultipartUploadResponse
   */
  uploadParts: BeginMultipartUploadResponseUploadParts;
}

export function BeginMultipartUploadResponseFromJSON(json: any): BeginMultipartUploadResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    file: FileDetailsFromJSON(json["file"]),
    uploadId: json["uploadId"],
    uploadParts: BeginMultipartUploadResponseUploadPartsFromJSON(json["uploadParts"])
  };
}

export function BeginMultipartUploadResponseToJSON(value?: BeginMultipartUploadResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    file: FileDetailsToJSON(value.file),
    uploadId: value.uploadId,
    uploadParts: BeginMultipartUploadResponseUploadPartsToJSON(value.uploadParts)
  };
}
