/* tslint:disable */
/* eslint-disable */
/**
 * upload-api
 * Upload API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: hello@upload.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// @ts-ignore
import { exists, mapValues } from "../runtime";

/**
 * Request body for CompleteUploadPart.
 *
 * See also: basic file uploads.
 * @export
 * @interface CompleteUploadPartRequest
 */
export interface CompleteUploadPartRequest {
  /**
   * File ETag.
   * @type {string}
   * @memberof CompleteUploadPartRequest
   */
  etag: string;
}

export function CompleteUploadPartRequestFromJSON(json: any): CompleteUploadPartRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    etag: json["etag"]
  };
}

export function CompleteUploadPartRequestToJSON(value?: CompleteUploadPartRequest | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    etag: value.etag
  };
}
