/* tslint:disable */
/* eslint-disable */
/**
 * upload-api
 * Upload API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: hello@upload.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// @ts-ignore
import { exists, mapValues } from "../runtime";

// @ts-ignore
import type { DeleteFolderRequest } from "./DeleteFolderRequest";
// @ts-ignore
import { DeleteFolderRequestFromJSON, DeleteFolderRequestToJSON } from "./DeleteFolderRequest";

/**
 * Request body for DeleteFolderBatch.
 * @export
 * @interface DeleteFolderBatchRequest
 */
export interface DeleteFolderBatchRequest {
  /**
   * Folders to delete.
   * @type {Array<DeleteFolderRequest>}
   * @memberof DeleteFolderBatchRequest
   */
  folders?: Array<DeleteFolderRequest>;
}

export function DeleteFolderBatchRequestFromJSON(json: any): DeleteFolderBatchRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    folders: !exists(json, "folders") ? undefined : (json["folders"] as Array<any>).map(DeleteFolderRequestFromJSON)
  };
}

export function DeleteFolderBatchRequestToJSON(value?: DeleteFolderBatchRequest | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    folders: value.folders === undefined ? undefined : (value.folders as Array<any>).map(DeleteFolderRequestToJSON)
  };
}
