/* tslint:disable */
/* eslint-disable */
/**
 * upload-api
 * Upload API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: hello@upload.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Specifies which files and folders relative to the `folderPath` to delete.
 *
 * - `"All"`: deletes the files and folders that match or descend the path specified by 'folderPath'.
 *
 * - `"Descendants"`: deletes the files and folders contained within 'folderPath' and below, but not the folder itself.
 *
 * - `"ThisFolder"`: deletes the folder specified by 'folderPath' if it contains no files and no sub-folders. Fails otherwise.
 *
 * Default: `"ThisFolder"`
 * @export
 */
export const DeleteFolderScope = {
  ThisFolder: "ThisFolder",
  Descendants: "Descendants",
  All: "All"
} as const;
export type DeleteFolderScope = typeof DeleteFolderScope[keyof typeof DeleteFolderScope];

export function DeleteFolderScopeFromJSON(json: any): DeleteFolderScope {
  return json as DeleteFolderScope;
}

export function DeleteFolderScopeToJSON(value?: DeleteFolderScope | null): any {
  return value as any;
}
