/* tslint:disable */
/* eslint-disable */
/**
 * upload-api
 * Upload API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: hello@upload.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// @ts-ignore
import { exists, mapValues } from "../runtime";

// @ts-ignore
import type { ErrorResponseError } from "./ErrorResponseError";
// @ts-ignore
import { ErrorResponseErrorFromJSON, ErrorResponseErrorToJSON } from "./ErrorResponseError";

/**
 * Response body for all error responses.
 * @export
 * @interface ErrorResponse
 */
export interface ErrorResponse {
  /**
   *
   * @type {ErrorResponseError}
   * @memberof ErrorResponse
   */
  error: ErrorResponseError;
}

export function ErrorResponseFromJSON(json: any): ErrorResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    error: ErrorResponseErrorFromJSON(json["error"])
  };
}

export function ErrorResponseToJSON(value?: ErrorResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    error: ErrorResponseErrorToJSON(value.error)
  };
}
