/* tslint:disable */
/* eslint-disable */
/**
 * upload-api
 * Upload API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: hello@upload.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The folder's status.
 * @export
 */
export const FolderStatus = {
  Ok: "Ok",
  Deleting: "Deleting"
} as const;
export type FolderStatus = typeof FolderStatus[keyof typeof FolderStatus];

export function FolderStatusFromJSON(json: any): FolderStatus {
  return json as FolderStatus;
}

export function FolderStatusToJSON(value?: FolderStatus | null): any {
  return value as any;
}
