/* tslint:disable */
/* eslint-disable */
/**
 * upload-api
 * Upload API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: hello@upload.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// @ts-ignore
import { exists, mapValues } from "../runtime";

// @ts-ignore
import type { FolderSettingsStorageLayerSummaryStorageLayer } from "./FolderSettingsStorageLayerSummaryStorageLayer";
// @ts-ignore
import {
  FolderSettingsStorageLayerSummaryStorageLayerFromJSON,
  FolderSettingsStorageLayerSummaryStorageLayerToJSON
} from "./FolderSettingsStorageLayerSummaryStorageLayer";
// @ts-ignore
import type { PublicPermissions } from "./PublicPermissions";
// @ts-ignore
import { PublicPermissionsFromJSON, PublicPermissionsToJSON } from "./PublicPermissions";

/**
 *
 * @export
 * @interface FolderSettingsStorageLayerSummary
 */
export interface FolderSettingsStorageLayerSummary {
  /**
   *
   * @type {string}
   * @memberof FolderSettingsStorageLayerSummary
   */
  description: string | null;
  /**
   *
   * @type {Array<PublicPermissions>}
   * @memberof FolderSettingsStorageLayerSummary
   */
  publicPermissions: Array<PublicPermissions> | null;
  /**
   *
   * @type {FolderSettingsStorageLayerSummaryStorageLayer}
   * @memberof FolderSettingsStorageLayerSummary
   */
  storageLayer: FolderSettingsStorageLayerSummaryStorageLayer | null;
}

export function FolderSettingsStorageLayerSummaryFromJSON(json: any): FolderSettingsStorageLayerSummary {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    description: json["description"],
    publicPermissions:
      json["publicPermissions"] === null
        ? null
        : (json["publicPermissions"] as Array<any>).map(PublicPermissionsFromJSON),
    storageLayer: FolderSettingsStorageLayerSummaryStorageLayerFromJSON(json["storageLayer"])
  };
}

export function FolderSettingsStorageLayerSummaryToJSON(value?: FolderSettingsStorageLayerSummary | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    description: value.description,
    publicPermissions:
      value.publicPermissions === null ? null : (value.publicPermissions as Array<any>).map(PublicPermissionsToJSON),
    storageLayer: FolderSettingsStorageLayerSummaryStorageLayerToJSON(value.storageLayer)
  };
}
