/* tslint:disable */
/* eslint-disable */
/**
 * upload-api
 * Upload API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: hello@upload.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// @ts-ignore
import { exists, mapValues } from "../runtime";

// @ts-ignore
import type { FolderSettingsInherited } from "./FolderSettingsInherited";
// @ts-ignore
import { FolderSettingsInheritedFromJSON, FolderSettingsInheritedToJSON } from "./FolderSettingsInherited";
// @ts-ignore
import type { FolderSettingsStorageLayerSummary } from "./FolderSettingsStorageLayerSummary";
// @ts-ignore
import {
  FolderSettingsStorageLayerSummaryFromJSON,
  FolderSettingsStorageLayerSummaryToJSON
} from "./FolderSettingsStorageLayerSummary";
// @ts-ignore
import type { FolderStatus } from "./FolderStatus";
// @ts-ignore
import { FolderStatusFromJSON, FolderStatusToJSON } from "./FolderStatus";

/**
 *
 * @export
 * @interface FolderDetails
 */
export interface FolderDetails {
  /**
   * Absolute path to a folder. Must begin with a `/`. Should not end with a `/`.
   * @type {string}
   * @memberof FolderDetails
   */
  folderPath: string;
  /**
   *
   * @type {FolderSettingsStorageLayerSummary}
   * @memberof FolderDetails
   */
  settings: FolderSettingsStorageLayerSummary;
  /**
   *
   * @type {FolderStatus}
   * @memberof FolderDetails
   */
  status: FolderStatus;
  /**
   *
   * @type {string}
   * @memberof FolderDetails
   */
  type: FolderDetailsTypeEnum;
  /**
   *
   * @type {FolderSettingsInherited}
   * @memberof FolderDetails
   */
  settingsInherited: FolderSettingsInherited;
}

/**
 * @export
 */
export const FolderDetailsTypeEnum = {
  Folder: "Folder"
} as const;
export type FolderDetailsTypeEnum = typeof FolderDetailsTypeEnum[keyof typeof FolderDetailsTypeEnum];

export function FolderDetailsFromJSON(json: any): FolderDetails {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    folderPath: json["folderPath"],
    settings: FolderSettingsStorageLayerSummaryFromJSON(json["settings"]),
    status: FolderStatusFromJSON(json["status"]),
    type: json["type"],
    settingsInherited: FolderSettingsInheritedFromJSON(json["settingsInherited"])
  };
}

export function FolderDetailsToJSON(value?: FolderDetails | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    folderPath: value.folderPath,
    settings: FolderSettingsStorageLayerSummaryToJSON(value.settings),
    status: FolderStatusToJSON(value.status),
    type: value.type,
    settingsInherited: FolderSettingsInheritedToJSON(value.settingsInherited)
  };
}
