/* tslint:disable */
/* eslint-disable */
/**
 * upload-api
 * Upload API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: hello@upload.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// @ts-ignore
import { exists, mapValues } from "../runtime";

// @ts-ignore
import type { AccountJobStatus } from "./AccountJobStatus";
// @ts-ignore
import { AccountJobStatusFromJSON, AccountJobStatusToJSON } from "./AccountJobStatus";
// @ts-ignore
import type { AccountJobType } from "./AccountJobType";
// @ts-ignore
import { AccountJobTypeFromJSON, AccountJobTypeToJSON } from "./AccountJobType";
// @ts-ignore
import type { JobSummaryError } from "./JobSummaryError";
// @ts-ignore
import { JobSummaryErrorFromJSON, JobSummaryErrorToJSON } from "./JobSummaryError";

/**
 * Summary information about an asynchronous background job (for example, a folder deletion).
 * @export
 * @interface JobSummary
 */
export interface JobSummary {
  /**
   * Your account ID.
   *
   * This is visible on the settings page:
   *
   * https://upload.io/dashboard/settings
   * @type {string}
   * @memberof JobSummary
   */
  accountId: string;
  /**
   * The number of times the job has been executed. Once the job has been successfully executed, no further attempts will be made.
   * @type {number}
   * @memberof JobSummary
   */
  attempts: number;
  /**
   * Epoch milliseconds (since midnight 1 January 1970, UTC).
   * @type {number}
   * @memberof JobSummary
   */
  created: number;
  /**
   *
   * @type {JobSummaryError}
   * @memberof JobSummary
   */
  error: JobSummaryError | null;
  /**
   * Job ID.
   * @type {string}
   * @memberof JobSummary
   */
  jobId: string;
  /**
   *
   * @type {AccountJobType}
   * @memberof JobSummary
   */
  jobType: AccountJobType;
  /**
   * Epoch milliseconds (since midnight 1 January 1970, UTC).
   * @type {number}
   * @memberof JobSummary
   */
  lastUpdated: number;
  /**
   * An arbitrary JSON object.
   * @type {{ [key: string]: any; }}
   * @memberof JobSummary
   */
  payload: { [key: string]: any };
  /**
   *
   * @type {AccountJobStatus}
   * @memberof JobSummary
   */
  status: AccountJobStatus;
}

export function JobSummaryFromJSON(json: any): JobSummary {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    accountId: json["accountId"],
    attempts: json["attempts"],
    created: json["created"],
    error: JobSummaryErrorFromJSON(json["error"]),
    jobId: json["jobId"],
    jobType: AccountJobTypeFromJSON(json["jobType"]),
    lastUpdated: json["lastUpdated"],
    payload: json["payload"],
    status: AccountJobStatusFromJSON(json["status"])
  };
}

export function JobSummaryToJSON(value?: JobSummary | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    accountId: value.accountId,
    attempts: value.attempts,
    created: value.created,
    error: JobSummaryErrorToJSON(value.error),
    jobId: value.jobId,
    jobType: AccountJobTypeToJSON(value.jobType),
    lastUpdated: value.lastUpdated,
    payload: value.payload,
    status: AccountJobStatusToJSON(value.status)
  };
}
