/* tslint:disable */
/* eslint-disable */
/**
 * upload-api
 * Upload API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: hello@upload.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// @ts-ignore
import { exists, mapValues } from "../runtime";

// @ts-ignore
import type { PickS3StorageExcludeKeyofS3StorageCredentialsBucket } from "./PickS3StorageExcludeKeyofS3StorageCredentialsBucket";
// @ts-ignore
import {
  PickS3StorageExcludeKeyofS3StorageCredentialsBucketFromJSON,
  PickS3StorageExcludeKeyofS3StorageCredentialsBucketToJSON
} from "./PickS3StorageExcludeKeyofS3StorageCredentialsBucket";

/**
 * From T, pick a set of properties whose keys are in the union K
 * @export
 * @interface PickS3StorageExcludeKeyofS3StorageCredentials
 */
export interface PickS3StorageExcludeKeyofS3StorageCredentials {
  /**
   * The type of this storage layer.
   * @type {string}
   * @memberof PickS3StorageExcludeKeyofS3StorageCredentials
   */
  type: PickS3StorageExcludeKeyofS3StorageCredentialsTypeEnum;
  /**
   *
   * @type {PickS3StorageExcludeKeyofS3StorageCredentialsBucket}
   * @memberof PickS3StorageExcludeKeyofS3StorageCredentials
   */
  bucket: PickS3StorageExcludeKeyofS3StorageCredentialsBucket;
  /**
   * If `true` then writes S3 objects with full `filePath` as key, prefixed with the `objectKeyPrefix`.
   *
   * If `false` then writes S3 objects using a relative `filePath` in relation to folder's path, prefixed with the `objectKeyPrefix`.
   * @type {boolean}
   * @memberof PickS3StorageExcludeKeyofS3StorageCredentials
   */
  useAbsolutePaths: boolean;
  /**
   * If `true` then raw file downloads are routed directly via the Upload CDN's edge nodes to the custom S3 bucket.
   *
   * If `false` then raw file downloads are routes via Upload's transformation pipelines, adding some latency to raw file downloads only.
   *
   * Note: if set to `true` then you must configure a "AWS::S3::BucketPolicy" for your S3 bucket, permitting access to Upload's CloudFront distribution. Alternatively, your S3 bucket must allow public file downloads.
   * @type {boolean}
   * @memberof PickS3StorageExcludeKeyofS3StorageCredentials
   */
  useDirectRawFileDelivery: boolean;
  /**
   * Only applicable if `useDirectRawFileDelivery` is set to `true`.
   * @type {boolean}
   * @memberof PickS3StorageExcludeKeyofS3StorageCredentials
   */
  useOriginAccessIdentity: boolean;
  /**
   * Enables S3 transfer acceleration, providing improved file upload speeds for larger files.
   *
   * Note: this setting must also be enabled on the S3 bucket.
   * @type {boolean}
   * @memberof PickS3StorageExcludeKeyofS3StorageCredentials
   */
  useTransferAcceleration: boolean;
}

/**
 * @export
 */
export const PickS3StorageExcludeKeyofS3StorageCredentialsTypeEnum = {
  S3: "S3"
} as const;
export type PickS3StorageExcludeKeyofS3StorageCredentialsTypeEnum = typeof PickS3StorageExcludeKeyofS3StorageCredentialsTypeEnum[keyof typeof PickS3StorageExcludeKeyofS3StorageCredentialsTypeEnum];

export function PickS3StorageExcludeKeyofS3StorageCredentialsFromJSON(
  json: any
): PickS3StorageExcludeKeyofS3StorageCredentials {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    type: json["type"],
    bucket: PickS3StorageExcludeKeyofS3StorageCredentialsBucketFromJSON(json["bucket"]),
    useAbsolutePaths: json["useAbsolutePaths"],
    useDirectRawFileDelivery: json["useDirectRawFileDelivery"],
    useOriginAccessIdentity: json["useOriginAccessIdentity"],
    useTransferAcceleration: json["useTransferAcceleration"]
  };
}

export function PickS3StorageExcludeKeyofS3StorageCredentialsToJSON(
  value?: PickS3StorageExcludeKeyofS3StorageCredentials | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    type: value.type,
    bucket: PickS3StorageExcludeKeyofS3StorageCredentialsBucketToJSON(value.bucket),
    useAbsolutePaths: value.useAbsolutePaths,
    useDirectRawFileDelivery: value.useDirectRawFileDelivery,
    useOriginAccessIdentity: value.useOriginAccessIdentity,
    useTransferAcceleration: value.useTransferAcceleration
  };
}
