/* tslint:disable */
/* eslint-disable */
/**
 * upload-api
 * Upload API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: hello@upload.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// @ts-ignore
import { exists, mapValues } from "../runtime";

// @ts-ignore
import type { AwsRegion } from "./AwsRegion";
// @ts-ignore
import { AwsRegionFromJSON, AwsRegionToJSON } from "./AwsRegion";

/**
 *
 * @export
 * @interface PickS3StorageExcludeKeyofS3StorageCredentialsBucket
 */
export interface PickS3StorageExcludeKeyofS3StorageCredentialsBucket {
  /**
   * AWS S3 Object Key.
   * @type {string}
   * @memberof PickS3StorageExcludeKeyofS3StorageCredentialsBucket
   */
  objectKeyPrefix: string;
  /**
   *
   * @type {AwsRegion}
   * @memberof PickS3StorageExcludeKeyofS3StorageCredentialsBucket
   */
  bucketRegion: AwsRegion;
  /**
   * AWS S3 Bucket Name.
   * @type {string}
   * @memberof PickS3StorageExcludeKeyofS3StorageCredentialsBucket
   */
  bucketName: string;
}

export function PickS3StorageExcludeKeyofS3StorageCredentialsBucketFromJSON(
  json: any
): PickS3StorageExcludeKeyofS3StorageCredentialsBucket {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    objectKeyPrefix: json["objectKeyPrefix"],
    bucketRegion: AwsRegionFromJSON(json["bucketRegion"]),
    bucketName: json["bucketName"]
  };
}

export function PickS3StorageExcludeKeyofS3StorageCredentialsBucketToJSON(
  value?: PickS3StorageExcludeKeyofS3StorageCredentialsBucket | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    objectKeyPrefix: value.objectKeyPrefix,
    bucketRegion: AwsRegionToJSON(value.bucketRegion),
    bucketName: value.bucketName
  };
}
