/* tslint:disable */
/* eslint-disable */
/**
 * upload-api
 * Upload API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: hello@upload.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// @ts-ignore
import { exists, mapValues } from "../runtime";

// @ts-ignore
import type { FileDownloadGrants } from "./FileDownloadGrants";
// @ts-ignore
import { FileDownloadGrantsFromJSON, FileDownloadGrantsToJSON } from "./FileDownloadGrants";

/**
 * Permissions applied to anonymous users who attempt to download files from a folder.
 *
 * Each folder can declare these permissions via its FolderSettings object.
 * @export
 * @interface PublicPermissionsGrants
 */
export interface PublicPermissionsGrants {
  /**
   *
   * @type {FileDownloadGrants}
   * @memberof PublicPermissionsGrants
   */
  file: FileDownloadGrants;
}

export function PublicPermissionsGrantsFromJSON(json: any): PublicPermissionsGrants {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    file: FileDownloadGrantsFromJSON(json["file"])
  };
}

export function PublicPermissionsGrantsToJSON(value?: PublicPermissionsGrants | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    file: FileDownloadGrantsToJSON(value.file)
  };
}
