/* tslint:disable */
/* eslint-disable */
/**
 * upload-api
 * Upload API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: hello@upload.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// @ts-ignore
import { exists, mapValues } from "../runtime";

// @ts-ignore
import type { PathPermissionScope } from "./PathPermissionScope";
// @ts-ignore
import { PathPermissionScopeFromJSON, PathPermissionScopeToJSON } from "./PathPermissionScope";
// @ts-ignore
import type { PublicPermissionsGrants } from "./PublicPermissionsGrants";
// @ts-ignore
import { PublicPermissionsGrantsFromJSON, PublicPermissionsGrantsToJSON } from "./PublicPermissionsGrants";

/**
 * Permissions applied to anonymous users who attempt to download files from a folder.
 *
 * Each folder can declare these permissions via its FolderSettings object.
 * @export
 * @interface PublicPermissions
 */
export interface PublicPermissions {
  /**
   *
   * @type {PublicPermissionsGrants}
   * @memberof PublicPermissions
   */
  permissions: PublicPermissionsGrants;
  /**
   *
   * @type {PathPermissionScope}
   * @memberof PublicPermissions
   */
  scope: PathPermissionScope;
}

export function PublicPermissionsFromJSON(json: any): PublicPermissions {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    permissions: PublicPermissionsGrantsFromJSON(json["permissions"]),
    scope: PathPermissionScopeFromJSON(json["scope"])
  };
}

export function PublicPermissionsToJSON(value?: PublicPermissions | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    permissions: PublicPermissionsGrantsToJSON(value.permissions),
    scope: PathPermissionScopeToJSON(value.scope)
  };
}
