/* tslint:disable */
/* eslint-disable */
/**
 * upload-api
 * Upload API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: hello@upload.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// @ts-ignore
import { exists, mapValues } from "../runtime";

/**
 *
 * @export
 * @interface S3StorageCredentials
 */
export interface S3StorageCredentials {
  /**
   * AWS Secret Access Key.
   * @type {string}
   * @memberof S3StorageCredentials
   */
  awsSecretKey: string;
  /**
   * AWS Access Key.
   * @type {string}
   * @memberof S3StorageCredentials
   */
  awsAccessKey: string;
}

export function S3StorageCredentialsFromJSON(json: any): S3StorageCredentials {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    awsSecretKey: json["awsSecretKey"],
    awsAccessKey: json["awsAccessKey"]
  };
}

export function S3StorageCredentialsToJSON(value?: S3StorageCredentials | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    awsSecretKey: value.awsSecretKey,
    awsAccessKey: value.awsAccessKey
  };
}
