/* tslint:disable */
/* eslint-disable */
/**
 * upload-api
 * Upload API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: hello@upload.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// @ts-ignore
import { exists, mapValues } from "../runtime";

// @ts-ignore
import type { SpecifiedFieldValueStorageLayerUpdateOrNullValue } from "./SpecifiedFieldValueStorageLayerUpdateOrNullValue";
// @ts-ignore
import {
  SpecifiedFieldValueStorageLayerUpdateOrNullValueFromJSON,
  SpecifiedFieldValueStorageLayerUpdateOrNullValueToJSON
} from "./SpecifiedFieldValueStorageLayerUpdateOrNullValue";

/**
 * This data type specifies the field must be updated.
 * @export
 * @interface SpecifiedFieldValueStorageLayerUpdateOrNull
 */
export interface SpecifiedFieldValueStorageLayerUpdateOrNull {
  /**
   * This field is always `true`.
   * @type {boolean}
   * @memberof SpecifiedFieldValueStorageLayerUpdateOrNull
   */
  set: SpecifiedFieldValueStorageLayerUpdateOrNullSetEnum;
  /**
   *
   * @type {SpecifiedFieldValueStorageLayerUpdateOrNullValue}
   * @memberof SpecifiedFieldValueStorageLayerUpdateOrNull
   */
  value: SpecifiedFieldValueStorageLayerUpdateOrNullValue | null;
}

/**
 * @export
 */
export const SpecifiedFieldValueStorageLayerUpdateOrNullSetEnum = {
  True: true
} as const;
export type SpecifiedFieldValueStorageLayerUpdateOrNullSetEnum = typeof SpecifiedFieldValueStorageLayerUpdateOrNullSetEnum[keyof typeof SpecifiedFieldValueStorageLayerUpdateOrNullSetEnum];

export function SpecifiedFieldValueStorageLayerUpdateOrNullFromJSON(
  json: any
): SpecifiedFieldValueStorageLayerUpdateOrNull {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    set: json["set"],
    value: SpecifiedFieldValueStorageLayerUpdateOrNullValueFromJSON(json["value"])
  };
}

export function SpecifiedFieldValueStorageLayerUpdateOrNullToJSON(
  value?: SpecifiedFieldValueStorageLayerUpdateOrNull | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    set: value.set,
    value: SpecifiedFieldValueStorageLayerUpdateOrNullValueToJSON(value.value)
  };
}
