/* tslint:disable */
/* eslint-disable */
/**
 * upload-api
 * Upload API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: hello@upload.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// @ts-ignore
import { exists, mapValues } from "../runtime";

/**
 * This data type specifies the field must be updated.
 * @export
 * @interface SpecifiedFieldValueFolderDescriptionOrNull
 */
export interface SpecifiedFieldValueFolderDescriptionOrNull {
  /**
   * This field is always `true`.
   * @type {boolean}
   * @memberof SpecifiedFieldValueFolderDescriptionOrNull
   */
  set: SpecifiedFieldValueFolderDescriptionOrNullSetEnum;
  /**
   * The value to set into the field.
   * @type {string}
   * @memberof SpecifiedFieldValueFolderDescriptionOrNull
   */
  value: string | null;
}

/**
 * @export
 */
export const SpecifiedFieldValueFolderDescriptionOrNullSetEnum = {
  True: true
} as const;
export type SpecifiedFieldValueFolderDescriptionOrNullSetEnum = typeof SpecifiedFieldValueFolderDescriptionOrNullSetEnum[keyof typeof SpecifiedFieldValueFolderDescriptionOrNullSetEnum];

export function SpecifiedFieldValueFolderDescriptionOrNullFromJSON(
  json: any
): SpecifiedFieldValueFolderDescriptionOrNull {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    set: json["set"],
    value: json["value"]
  };
}

export function SpecifiedFieldValueFolderDescriptionOrNullToJSON(
  value?: SpecifiedFieldValueFolderDescriptionOrNull | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    set: value.set,
    value: value.value
  };
}
