/* tslint:disable */
/* eslint-disable */
/**
 * upload-api
 * Upload API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: hello@upload.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// @ts-ignore
import { exists, mapValues } from "../runtime";

// @ts-ignore
import type { SpecifiedFieldValueFolderDescriptionOrNull } from "./SpecifiedFieldValueFolderDescriptionOrNull";
// @ts-ignore
import {
  SpecifiedFieldValueFolderDescriptionOrNullFromJSON,
  SpecifiedFieldValueFolderDescriptionOrNullToJSON
} from "./SpecifiedFieldValueFolderDescriptionOrNull";
// @ts-ignore
import type { UnspecifiedFieldValue } from "./UnspecifiedFieldValue";
// @ts-ignore
import { UnspecifiedFieldValueFromJSON, UnspecifiedFieldValueToJSON } from "./UnspecifiedFieldValue";

/**
 *
 * @export
 * @interface UpdatableFieldFolderDescriptionOrNull
 */
export interface UpdatableFieldFolderDescriptionOrNull {
  /**
   * This field is always `true`.
   * @type {boolean}
   * @memberof UpdatableFieldFolderDescriptionOrNull
   */
  set: UpdatableFieldFolderDescriptionOrNullSetEnum;
  /**
   * The value to set into the field.
   * @type {string}
   * @memberof UpdatableFieldFolderDescriptionOrNull
   */
  value: string | null;
}

/**
 * @export
 */
export const UpdatableFieldFolderDescriptionOrNullSetEnum = {
  True: true
} as const;
export type UpdatableFieldFolderDescriptionOrNullSetEnum = typeof UpdatableFieldFolderDescriptionOrNullSetEnum[keyof typeof UpdatableFieldFolderDescriptionOrNullSetEnum];

export function UpdatableFieldFolderDescriptionOrNullFromJSON(json: any): UpdatableFieldFolderDescriptionOrNull {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    set: json["set"],
    value: json["value"]
  };
}

export function UpdatableFieldFolderDescriptionOrNullToJSON(value?: UpdatableFieldFolderDescriptionOrNull | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    set: value.set,
    value: value.value
  };
}
