/* tslint:disable */
/* eslint-disable */
/**
 * upload-api
 * Upload API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: hello@upload.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// @ts-ignore
import { exists, mapValues } from "../runtime";

// @ts-ignore
import type { SpecifiedFieldValueStorageLayerUpdateOrNull } from "./SpecifiedFieldValueStorageLayerUpdateOrNull";
// @ts-ignore
import {
  SpecifiedFieldValueStorageLayerUpdateOrNullFromJSON,
  SpecifiedFieldValueStorageLayerUpdateOrNullToJSON
} from "./SpecifiedFieldValueStorageLayerUpdateOrNull";
// @ts-ignore
import type { SpecifiedFieldValueStorageLayerUpdateOrNullValue } from "./SpecifiedFieldValueStorageLayerUpdateOrNullValue";
// @ts-ignore
import {
  SpecifiedFieldValueStorageLayerUpdateOrNullValueFromJSON,
  SpecifiedFieldValueStorageLayerUpdateOrNullValueToJSON
} from "./SpecifiedFieldValueStorageLayerUpdateOrNullValue";
// @ts-ignore
import type { UnspecifiedFieldValue } from "./UnspecifiedFieldValue";
// @ts-ignore
import { UnspecifiedFieldValueFromJSON, UnspecifiedFieldValueToJSON } from "./UnspecifiedFieldValue";

/**
 *
 * @export
 * @interface UpdatableFieldStorageLayerUpdateOrNull
 */
export interface UpdatableFieldStorageLayerUpdateOrNull {
  /**
   * This field is always `true`.
   * @type {boolean}
   * @memberof UpdatableFieldStorageLayerUpdateOrNull
   */
  set: UpdatableFieldStorageLayerUpdateOrNullSetEnum;
  /**
   *
   * @type {SpecifiedFieldValueStorageLayerUpdateOrNullValue}
   * @memberof UpdatableFieldStorageLayerUpdateOrNull
   */
  value: SpecifiedFieldValueStorageLayerUpdateOrNullValue | null;
}

/**
 * @export
 */
export const UpdatableFieldStorageLayerUpdateOrNullSetEnum = {
  True: true
} as const;
export type UpdatableFieldStorageLayerUpdateOrNullSetEnum = typeof UpdatableFieldStorageLayerUpdateOrNullSetEnum[keyof typeof UpdatableFieldStorageLayerUpdateOrNullSetEnum];

export function UpdatableFieldStorageLayerUpdateOrNullFromJSON(json: any): UpdatableFieldStorageLayerUpdateOrNull {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    set: json["set"],
    value: SpecifiedFieldValueStorageLayerUpdateOrNullValueFromJSON(json["value"])
  };
}

export function UpdatableFieldStorageLayerUpdateOrNullToJSON(
  value?: UpdatableFieldStorageLayerUpdateOrNull | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    set: value.set,
    value: SpecifiedFieldValueStorageLayerUpdateOrNullValueToJSON(value.value)
  };
}
