/* tslint:disable */
/* eslint-disable */
/**
 * upload-api
 * Upload API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: hello@upload.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// @ts-ignore
import { exists, mapValues } from "../runtime";

// @ts-ignore
import type { PublicPermissions } from "./PublicPermissions";
// @ts-ignore
import { PublicPermissionsFromJSON, PublicPermissionsToJSON } from "./PublicPermissions";
// @ts-ignore
import type { SpecifiedFieldValuePublicPermissionsArrayOrNull } from "./SpecifiedFieldValuePublicPermissionsArrayOrNull";
// @ts-ignore
import {
  SpecifiedFieldValuePublicPermissionsArrayOrNullFromJSON,
  SpecifiedFieldValuePublicPermissionsArrayOrNullToJSON
} from "./SpecifiedFieldValuePublicPermissionsArrayOrNull";
// @ts-ignore
import type { UnspecifiedFieldValue } from "./UnspecifiedFieldValue";
// @ts-ignore
import { UnspecifiedFieldValueFromJSON, UnspecifiedFieldValueToJSON } from "./UnspecifiedFieldValue";

/**
 *
 * @export
 * @interface UpdatableFieldPublicPermissionsArrayOrNull
 */
export interface UpdatableFieldPublicPermissionsArrayOrNull {
  /**
   * This field is always `true`.
   * @type {boolean}
   * @memberof UpdatableFieldPublicPermissionsArrayOrNull
   */
  set: UpdatableFieldPublicPermissionsArrayOrNullSetEnum;
  /**
   * The value to set into the field.
   * @type {Array<PublicPermissions>}
   * @memberof UpdatableFieldPublicPermissionsArrayOrNull
   */
  value: Array<PublicPermissions> | null;
}

/**
 * @export
 */
export const UpdatableFieldPublicPermissionsArrayOrNullSetEnum = {
  True: true
} as const;
export type UpdatableFieldPublicPermissionsArrayOrNullSetEnum = typeof UpdatableFieldPublicPermissionsArrayOrNullSetEnum[keyof typeof UpdatableFieldPublicPermissionsArrayOrNullSetEnum];

export function UpdatableFieldPublicPermissionsArrayOrNullFromJSON(
  json: any
): UpdatableFieldPublicPermissionsArrayOrNull {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    set: json["set"],
    value: json["value"] === null ? null : (json["value"] as Array<any>).map(PublicPermissionsFromJSON)
  };
}

export function UpdatableFieldPublicPermissionsArrayOrNullToJSON(
  value?: UpdatableFieldPublicPermissionsArrayOrNull | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    set: value.set,
    value: value.value === null ? null : (value.value as Array<any>).map(PublicPermissionsToJSON)
  };
}
