/* tslint:disable */
/* eslint-disable */
/**
 * upload-api
 * Upload API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: hello@upload.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// @ts-ignore
import { exists, mapValues } from "../runtime";

/**
 * Identifies the UploadPart indexes that still need uploading for an active multipart file upload.
 *
 * See also: basic file uploads.
 * @export
 * @interface UploadPartList
 */
export interface UploadPartList {
  /**
   * Indexes of the remaining parts to upload.
   *
   * These indexes can be used as the `uploadPartIndex` parameter in the GetUploadPart and CompleteUploadPart endpoints.
   * @type {Array<number>}
   * @memberof UploadPartList
   */
  remainingUploadParts: Array<number>;
}

export function UploadPartListFromJSON(json: any): UploadPartList {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    remainingUploadParts: json["remainingUploadParts"]
  };
}

export function UploadPartListToJSON(value?: UploadPartList | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    remainingUploadParts: value.remainingUploadParts
  };
}
