/* tslint:disable */
/* eslint-disable */
/**
 * upload-api
 * Upload API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: hello@upload.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// @ts-ignore
import { exists, mapValues } from "../runtime";

// @ts-ignore
import type { StorageLayerSummary } from "./StorageLayerSummary";
// @ts-ignore
import { StorageLayerSummaryFromJSON, StorageLayerSummaryToJSON } from "./StorageLayerSummary";

/**
 *
 * @export
 * @interface WithFolderPathStorageLayerSummary
 */
export interface WithFolderPathStorageLayerSummary {
  /**
   * Absolute path to a folder. Must begin with a `/`. Should not end with a `/`.
   * @type {string}
   * @memberof WithFolderPathStorageLayerSummary
   */
  folderPath: string;
  /**
   *
   * @type {StorageLayerSummary}
   * @memberof WithFolderPathStorageLayerSummary
   */
  value: StorageLayerSummary;
}

export function WithFolderPathStorageLayerSummaryFromJSON(json: any): WithFolderPathStorageLayerSummary {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    folderPath: json["folderPath"],
    value: StorageLayerSummaryFromJSON(json["value"])
  };
}

export function WithFolderPathStorageLayerSummaryToJSON(value?: WithFolderPathStorageLayerSummary | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    folderPath: value.folderPath,
    value: StorageLayerSummaryToJSON(value.value)
  };
}
