/* tslint:disable */
/* eslint-disable */
/**
 * upload-api
 * Upload API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: hello@upload.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// @ts-ignore
import { exists, mapValues } from "../runtime";

// @ts-ignore
import type { PublicPermissions } from "./PublicPermissions";
// @ts-ignore
import { PublicPermissionsFromJSON, PublicPermissionsToJSON } from "./PublicPermissions";

/**
 *
 * @export
 * @interface WithFolderPathPublicPermissionsArray
 */
export interface WithFolderPathPublicPermissionsArray {
  /**
   * Absolute path to a folder. Must begin with a `/`. Should not end with a `/`.
   * @type {string}
   * @memberof WithFolderPathPublicPermissionsArray
   */
  folderPath: string;
  /**
   *
   * @type {Array<PublicPermissions>}
   * @memberof WithFolderPathPublicPermissionsArray
   */
  value: Array<PublicPermissions>;
}

export function WithFolderPathPublicPermissionsArrayFromJSON(json: any): WithFolderPathPublicPermissionsArray {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    folderPath: json["folderPath"],
    value: (json["value"] as Array<any>).map(PublicPermissionsFromJSON)
  };
}

export function WithFolderPathPublicPermissionsArrayToJSON(value?: WithFolderPathPublicPermissionsArray | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    folderPath: value.folderPath,
    value: (value.value as Array<any>).map(PublicPermissionsToJSON)
  };
}
